#!/bin/bash
BUILD_TYPE=$1
shift
cmake . -B build/ -G "Unix Makefiles" -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DBUILD_CURL_EXE=OFF "$@"
