name: build
on: [ push ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull submodules
        run: |
          git submodule init
          git submodule update
      - name: install dependencies
        run: |
          sudo apt-get install libasio-dev libssh2-1-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev
      - name: configure cmake
        run: |
          ${{github.workspace}}/unix-genprojects.sh Release -DWST_BUILD_CLIENTS=ON
      - name: build
        run: |
          make -C ${{github.workspace}}/build -j 8